### ISSUE TITLE
Instance variables should hold state with the same life span as the object

### ISSUE THREAD

**Issue by sveinn** [appfolio/great_code#5]
**Wanted**: Code example. 

**[Bounty](http://en.wikipedia.org/wiki/Bounty_%28reward%29)**:   _3x :cookie:_

**Comment by dtognazzini** [comment]
http://programmers.stackexchange.com/questions/214851/ruby-when-to-use-instance-variables-vs-parameters-between-methods

**Comment by dtognazzini** [comment]
README was updated with above link.
